# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from circuitid_python.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    AUTHENTICATION = "Authentication"
    ACCEPTED_SENDERS = "Accepted Senders"
    ANNOUNCEMENTS = "Announcements"
    APP_MARKETPLACE = "App Marketplace"
    CONTACTS = "Contacts"
    CALL_QUEUES = "Call Queues"
    CALL_QUEUE_AGENTS = "Call Queue Agents"
    CHAT_ROOMS = "Chat Rooms"
    CLIENTS = "Clients"
    CONVERSATIONS = "Conversations"
    CONVERSATION_MESSAGES = "Conversation Messages"
    CONFERENCE_ROOMS = "Conference Rooms"
    CONFERENCE_NUMBERS = "Conference Numbers"
    CUSTOMERS = "Customers"
    DEVELOPER_APPS = "Developer Apps"
    DEVELOPER_APP_SUBSCRIPTIONS = "Developer App Subscriptions"
    DIRECTORIES = "Directories"
    DOMAINS = "Domains"
    DNS_RECORDS = "DNS Records"
    FAXES = "Faxes"
    FAX_ACCOUNTS = "Fax Accounts"
    FIND_NUMBERS = "Find Numbers"
    FIREWALL = "Firewall"
    GROUPS = "Groups"
    GROUP_MEMBERS = "Group Members"
    HOLIDAYS = "Holidays"
    INFO = "Info"
    INVOICE_ITEMS = "Invoice Items"
    INVOICES = "Invoices"
    LICENSES = "Licenses"
    MENUS = "Menus"
    MENU_OPTIONS = "Menu Options"
    MESSAGE_CAMPAIGNS = "Message Campaigns"
    MESSAGE_BRANDS = "Message Brands"
    NUMBERS = "Numbers"
    NUMBER_PORTS = "Number Ports"
    OFFICES = "Offices"
    PHONE_INBOUND_RULES = "Phone Inbound Rules"
    PHONE_OUTBOUND_RULES = "Phone Outbound Rules"
    PHONE_INBOUND_RULE_ACTIONS = "Phone Inbound Rule Actions"
    PHONE_OUTBOUND_RULE_ACTIONS = "Phone Outbound Rule Actions"
    RATE_CENTERS = "Rate Centers"
    SERVERS = "Servers"
    TIME_SCHEDULES = "Time Schedules"
    USERS = "Users"
    USER_TOKENS = "User Tokens"
    VIRTUAL_EXTENSIONS = "Virtual Extensions"
    VOICEMAIL = "Voicemail"
